"""Initial migration

Revision ID: 379c6ff8ff65
Revises: 
Create Date: 2026-02-17 17:58:00.156846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379c6ff8ff65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_provider_id'), 'user', ['provider_id'], unique=True)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_table('alert_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_job_id'), 'alert_job', ['id'], unique=False)
    op.create_index(op.f('ix_alert_job_job_name'), 'alert_job', ['job_name'], unique=False)
    op.create_index(op.f('ix_alert_job_user_id'), 'alert_job', ['user_id'], unique=False)
    op.create_table('job_offer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_title', sa.String(length=255), nullable=False),
    sa.Column('offer_link', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id_alert_job', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_alert_job'], ['alert_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offer_id'), 'job_offer', ['id'], unique=False)
    op.create_index(op.f('ix_job_offer_id_alert_job'), 'job_offer', ['id_alert_job'], unique=False)
    op.create_index(op.f('ix_job_offer_offer_link'), 'job_offer', ['offer_link'], unique=False)
    op.create_index(op.f('ix_job_offer_offer_title'), 'job_offer', ['offer_title'], unique=False)
    op.create_index(op.f('ix_job_offer_source'), 'job_offer', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_offer_source'), table_name='job_offer')
    op.drop_index(op.f('ix_job_offer_offer_title'), table_name='job_offer')
    op.drop_index(op.f('ix_job_offer_offer_link'), table_name='job_offer')
    op.drop_index(op.f('ix_job_offer_id_alert_job'), table_name='job_offer')
    op.drop_index(op.f('ix_job_offer_id'), table_name='job_offer')
    op.drop_table('job_offer')
    op.drop_index(op.f('ix_alert_job_user_id'), table_name='alert_job')
    op.drop_index(op.f('ix_alert_job_job_name'), table_name='alert_job')
    op.drop_index(op.f('ix_alert_job_id'), table_name='alert_job')
    op.drop_table('alert_job')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_provider_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
