"""upgrade table job_offer

Revision ID: ccc8d912ce31
Revises: df4b69481897
Create Date: 2026-02-26 19:56:23.139875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc8d912ce31'
down_revision: Union[str, Sequence[str], None] = 'df4b69481897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offer', sa.Column('category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offer', 'category')
    # ### end Alembic commands ###
