"""update table job_offer

Revision ID: df4b69481897
Revises: 58bdefbc8d80
Create Date: 2026-02-25 19:01:03.887395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4b69481897'
down_revision: Union[str, Sequence[str], None] = '58bdefbc8d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_job_id'), table_name='alert_job')
    op.drop_index(op.f('ix_alert_job_job_name'), table_name='alert_job')
    op.drop_index(op.f('ix_alert_job_user_id'), table_name='alert_job')

    # 2. L'ARME ABSOLUE : Supprime la table ET les contraintes liées (FKey dans job_offer)
    op.execute('DROP TABLE IF EXISTS alert_job CASCADE')
    op.add_column('job_offer', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.add_column('job_offer', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('job_offer', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('job_offer', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('job_offer', sa.Column('min_xp', sa.Integer(), nullable=True))
    op.add_column('job_offer', sa.Column('level_required', sa.String(length=50), nullable=True))
    op.add_column('job_offer', sa.Column('skills_required', sa.JSON(), nullable=True))
    op.add_column('job_offer', sa.Column('raw_url', sa.String(length=500), nullable=False))
    op.add_column('job_offer', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('job_offer', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('job_offer', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_job_offer_id_alert_job'), table_name='job_offer')
    op.drop_index(op.f('ix_job_offer_offer_link'), table_name='job_offer')
    op.drop_index(op.f('ix_job_offer_offer_title'), table_name='job_offer')
    op.drop_index(op.f('ix_job_offer_source'), table_name='job_offer')
    op.create_unique_constraint(None, 'job_offer', ['fingerprint'])
    op.drop_column('job_offer', 'offer_link')
    op.drop_column('job_offer', 'source')
    op.drop_column('job_offer', 'id_alert_job')
    op.drop_column('job_offer', 'offer_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offer', sa.Column('offer_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('job_offer', sa.Column('id_alert_job', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('job_offer', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('job_offer', sa.Column('offer_link', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('job_offer_id_alert_job_fkey'), 'job_offer', 'alert_job', ['id_alert_job'], ['id'])
    op.drop_constraint(None, 'job_offer', type_='unique')
    op.create_index(op.f('ix_job_offer_source'), 'job_offer', ['source'], unique=False)
    op.create_index(op.f('ix_job_offer_offer_title'), 'job_offer', ['offer_title'], unique=False)
    op.create_index(op.f('ix_job_offer_offer_link'), 'job_offer', ['offer_link'], unique=False)
    op.create_index(op.f('ix_job_offer_id_alert_job'), 'job_offer', ['id_alert_job'], unique=False)
    op.drop_column('job_offer', 'posted_at')
    op.drop_column('job_offer', 'created_at')
    op.drop_column('job_offer', 'description')
    op.drop_column('job_offer', 'raw_url')
    op.drop_column('job_offer', 'skills_required')
    op.drop_column('job_offer', 'level_required')
    op.drop_column('job_offer', 'min_xp')
    op.drop_column('job_offer', 'location')
    op.drop_column('job_offer', 'company')
    op.drop_column('job_offer', 'title')
    op.drop_column('job_offer', 'fingerprint')
    op.create_table('alert_job',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('alert_job_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_job_pkey'))
    )
    op.create_index(op.f('ix_alert_job_user_id'), 'alert_job', ['user_id'], unique=False)
    op.create_index(op.f('ix_alert_job_job_name'), 'alert_job', ['job_name'], unique=False)
    op.create_index(op.f('ix_alert_job_id'), 'alert_job', ['id'], unique=False)
    # ### end Alembic commands ###
